services:
  # PostgreSQL Service
  postgres:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data  # Attach named volume to persist data

  # Node.js Application Service
  app:
    build:
      context: ./backend  # Adjust the path to your 'backend' directory relative to the location of docker-compose.yml
      dockerfile: Dockerfile  # Specify Dockerfile if not named 'Dockerfile'
    container_name: app
    environment:
      - JWT_SECRET=your_jwt_secret_key
      - JWT_EXPIRATION=1h
      - DATABASE_URL=postgres://user:password@postgres:5432/db  # Connection string to connect to PostgreSQL
    ports:
      - "5000:5000"  # Map host port to container port
    depends_on:
      - postgres  # Ensures PostgreSQL starts before app
    volumes:
      - ./backend:/app  # Mount the 'backend' folder on your local machine to /app in the container

volumes:
  postgres-data:  # Define the named volume
