version: '3.8'

services:
  # PostgreSQL Service
  postgres:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data  # Attach named volume to persist data

  # Node.js Application Service (Backend)
  app:
    build:
      context: ./backend  # Path to your backend directory
      dockerfile: Dockerfile  # Specify Dockerfile if it's named 'Dockerfile'
    container_name: app
    environment:
      - JWT_SECRET=your_jwt_secret_key
      - JWT_EXPIRATION=1h
      - DATABASE_URL=postgres://user:password@postgres:5432/db  # Connection string to PostgreSQL
    ports:
      - "5000:5000"  # Map host port to container port
    depends_on:
      - postgres  # Ensures PostgreSQL starts before the app
    volumes:
      - ./backend:/app  # Mount your local 'backend' folder to /app in the container

  # React Frontend Service
  frontend:
    build:
      context: ./frontend  # Path to your frontend directory
      dockerfile: Dockerfile  # Specify Dockerfile if it's named 'Dockerfile'
    container_name: frontend
    environment:
      - REACT_APP_API_URL=http://app:5000  # Point to backend service, inside the container
    ports:
      - "3000:3000"  # Map host port 3000 to container port 3000 for the React app
    depends_on:
      - app  # Ensures the app (backend) starts before the frontend
    volumes:
      - ./frontend:/app

volumes:
  postgres-data:  # Define the named volume to persist PostgreSQL data
